spring: 
    application:
      name: CONFIG-SERVER 
    cloud:
      config:        server:
          git:
            default-label: main
            uri: https://github.com/myAbdi/cloud-config-server
            
server:   port: 9999
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost